/*
 * Sandpiles.java
 *
 * Created on October 1, 2008, 10:35 PM
 */



/**
 *
 * @author  headb
 */


import javax.swing.Timer;
import javax.swing.JLabel;
import java.awt.CardLayout;

//import java.awt.event.MouseListener;

//import java.awt.event.MouseAdapter;
//import java.awt.event.KeyEvent;
//import java.awt.event.KeyListener;
//import java.awt.event.KeyAdapter;


public class Sandpiles extends javax.swing.JFrame {
	private static final String ADD_SAND_STATE = "Add Sand";
	private static final String DEL_SAND_STATE = "Remove Sand";
	private static final String MAKE_GRID_STATE = "Make Grid";
	private static final String MAKE_HEX_GRID_STATE = "Make Hex Grid";
	private static final String ADD_VERTEX_STATE = "Add Vertex";
	private static final String DEL_VERTEX_STATE = "Delete Vertex";
	private static final String ADD_EDGE_STATE = "Add Edge";
	private static final String DEL_EDGE_STATE = "Delete Edge";
	private static final String ADD_UNDI_EDGE_STATE = "Add Undirected Edge";
	private static final String DEL_UNDI_EDGE_STATE = "Delete Undirected Edge";
	
	
	
    private boolean running = false;
    private Timer runTimer;
    
    /** Creates new form Sandpiles */
    public Sandpiles() {
        initComponents();
        runTimer = new Timer(10,sandpileViewPanel);
		//controlStateComboBox.addActionListener((SandpilePanel) sandpileViewPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jComboBox1 = new javax.swing.JComboBox();
        addSandOptionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numOfGrainsField = new javax.swing.JTextField();
        makeGridOptionsPanel = new javax.swing.JPanel();
        gridSizeLabel = new javax.swing.JLabel();
        gridRowsField = new javax.swing.JTextField();
        gridSizeCrossLabel = new javax.swing.JLabel();
        gridColsField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nBorderComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        sBorderComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        eBorderComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        wBorderComboBox = new javax.swing.JComboBox();
        addEdgeOptionsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        weightField = new javax.swing.JTextField();
        blankOptionsPanel = new javax.swing.JPanel();
        stepButton = new javax.swing.JButton();
        runButton = new javax.swing.JToggleButton();
        quitButton = new javax.swing.JButton();
        delaySlider = new javax.swing.JSlider();
        delayLabel = new javax.swing.JLabel();
        delayTextField = new javax.swing.JTextField();
        controlStateComboBox = new javax.swing.JComboBox();
        maxSandButton = new javax.swing.JButton();
        clearSandButton = new javax.swing.JButton();
        addOneGrainEverywhereButton = new javax.swing.JButton();
        optionsContainerPanel = new javax.swing.JPanel();
        repaintCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        sandpileViewPanel = new SandpilePanel();
        colorCheckBox = new javax.swing.JCheckBox();
        labelsCheckBox = new javax.swing.JCheckBox();
        duelConfigButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("# of Grains:");

        numOfGrainsField.setText("1");
        numOfGrainsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfGrainsFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout addSandOptionsPanelLayout = new org.jdesktop.layout.GroupLayout(addSandOptionsPanel);
        addSandOptionsPanel.setLayout(addSandOptionsPanelLayout);
        addSandOptionsPanelLayout.setHorizontalGroup(
            addSandOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addSandOptionsPanelLayout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(numOfGrainsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        addSandOptionsPanelLayout.setVerticalGroup(
            addSandOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addSandOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel1)
                .add(numOfGrainsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        gridSizeLabel.setText("Grid Size:");

        gridRowsField.setText("5");
        gridRowsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridRowsFieldActionPerformed(evt);
            }
        });
        gridRowsField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gridRowsFieldPropertyChange(evt);
            }
        });

        gridSizeCrossLabel.setText("X");

        gridColsField.setText("5");
        gridColsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridColsFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("N Border:");

        nBorderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directed", "Undirected", "None" }));
        nBorderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBorderComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("S Border:");

        sBorderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directed", "Undirected", "None" }));
        sBorderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBorderComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("E Border:");

        eBorderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directed", "Undirected", "None" }));
        eBorderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBorderComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("W Border:");

        wBorderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directed", "Undirected", "None" }));
        wBorderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wBorderComboBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout makeGridOptionsPanelLayout = new org.jdesktop.layout.GroupLayout(makeGridOptionsPanel);
        makeGridOptionsPanel.setLayout(makeGridOptionsPanelLayout);
        makeGridOptionsPanelLayout.setHorizontalGroup(
            makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(makeGridOptionsPanelLayout.createSequentialGroup()
                .add(gridSizeLabel)
                .add(2, 2, 2)
                .add(gridRowsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(gridSizeCrossLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(gridColsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(makeGridOptionsPanelLayout.createSequentialGroup()
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(sBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(makeGridOptionsPanelLayout.createSequentialGroup()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(makeGridOptionsPanelLayout.createSequentialGroup()
                .add(makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(wBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(eBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        makeGridOptionsPanelLayout.setVerticalGroup(
            makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(makeGridOptionsPanelLayout.createSequentialGroup()
                .add(makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(gridSizeLabel)
                    .add(gridRowsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(gridSizeCrossLabel)
                    .add(gridColsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(nBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(sBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(eBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeGridOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(wBorderComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLabel2.setText("Weight:");

        weightField.setText("1");
        weightField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout addEdgeOptionsPanelLayout = new org.jdesktop.layout.GroupLayout(addEdgeOptionsPanel);
        addEdgeOptionsPanel.setLayout(addEdgeOptionsPanelLayout);
        addEdgeOptionsPanelLayout.setHorizontalGroup(
            addEdgeOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addEdgeOptionsPanelLayout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(weightField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        addEdgeOptionsPanelLayout.setVerticalGroup(
            addEdgeOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addEdgeOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel2)
                .add(weightField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout blankOptionsPanelLayout = new org.jdesktop.layout.GroupLayout(blankOptionsPanel);
        blankOptionsPanel.setLayout(blankOptionsPanelLayout);
        blankOptionsPanelLayout.setHorizontalGroup(
            blankOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 55, Short.MAX_VALUE)
        );
        blankOptionsPanelLayout.setVerticalGroup(
            blankOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 17, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sandpiles");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("sandpilesMainFrame"); // NOI18N

        stepButton.setText("Step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });
        stepButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stepButtonMouseClicked(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        delaySlider.setMaximum(1000);
        delaySlider.setToolTipText("Adjusts the number of milliseconds between each update.");
        delaySlider.setValue(100);
        delaySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                delaySliderStateChanged(evt);
            }
        });

        delayLabel.setText("Delay:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, delaySlider, org.jdesktop.beansbinding.ELProperty.create("${value}"), delayTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        delayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delayTextFieldActionPerformed(evt);
            }
        });

        controlStateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ADD_VERTEX_STATE, DEL_VERTEX_STATE, ADD_EDGE_STATE, DEL_EDGE_STATE, ADD_UNDI_EDGE_STATE, DEL_UNDI_EDGE_STATE, ADD_SAND_STATE, DEL_SAND_STATE, MAKE_GRID_STATE, MAKE_HEX_GRID_STATE }));
        controlStateComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                controlStateComboBoxItemStateChanged(evt);
            }
        });
        controlStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlStateComboBoxActionPerformed(evt);
            }
        });

        maxSandButton.setText("Add Max Stable Config");
        maxSandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxSandButtonActionPerformed(evt);
            }
        });

        clearSandButton.setText("Clear Sand");
        clearSandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSandButtonActionPerformed(evt);
            }
        });

        addOneGrainEverywhereButton.setText("Add 1 Grain Everywhere");
        addOneGrainEverywhereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOneGrainEverywhereButtonActionPerformed(evt);
            }
        });

        optionsContainerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        optionsContainerPanel.setLayout(new java.awt.CardLayout());
        optionsContainerPanel.add(blankOptionsPanel, ADD_VERTEX_STATE);
        //optionsContainerPanel.add(blankOptionsPanel, DEL_VERTEX_STATE);
        optionsContainerPanel.add(makeGridOptionsPanel, MAKE_GRID_STATE);
        optionsContainerPanel.add(addSandOptionsPanel, ADD_SAND_STATE);
        //optionsContainerPanel.add(addSandOptionsPanel, DEL_SAND_STATE);
        optionsContainerPanel.add(addEdgeOptionsPanel, ADD_EDGE_STATE);
        //optionsContainerPanel.add(addEdgeOptionsPanel, DEL_EDGE_STATE);
        //optionsContainerPanel.add(addEdgeOptionsPanel, ADD_UNDI_EDGE_STATE);
        //optionsContainerPanel.add(addEdgeOptionsPanel, DEL_UNDI_EDGE_STATE);

        repaintCheckBox.setSelected(true);
        repaintCheckBox.setText("Repaint");
        repaintCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repaintCheckBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        sandpileViewPanel.setBackground(new java.awt.Color(0, 0, 0));
        sandpileViewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        sandpileViewPanel.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        sandpileViewPanel.setPreferredSize(new java.awt.Dimension(2000, 2000));
        sandpileViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sandpileViewPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sandpileViewPanelMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout sandpileViewPanelLayout = new org.jdesktop.layout.GroupLayout(sandpileViewPanel);
        sandpileViewPanel.setLayout(sandpileViewPanelLayout);
        sandpileViewPanelLayout.setHorizontalGroup(
            sandpileViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1996, Short.MAX_VALUE)
        );
        sandpileViewPanelLayout.setVerticalGroup(
            sandpileViewPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1996, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(sandpileViewPanel);

        colorCheckBox.setSelected(true);
        colorCheckBox.setText("Color");
        colorCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorCheckBoxActionPerformed(evt);
            }
        });

        labelsCheckBox.setSelected(true);
        labelsCheckBox.setText("Labels");
        labelsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelsCheckBoxActionPerformed(evt);
            }
        });

        duelConfigButton.setText("Duel Config");
        duelConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duelConfigButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(optionsContainerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(controlStateComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(clearSandButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 198, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, duelConfigButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, quitButton)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, maxSandButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, addOneGrainEverywhereButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(repaintCheckBox)
                                    .add(colorCheckBox)
                                    .add(labelsCheckBox)
                                    .add(delayLabel))
                                .add(10, 10, 10)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, stepButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, runButton))
                                    .add(delayTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(delaySlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(stepButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(runButton))
                    .add(layout.createSequentialGroup()
                        .add(repaintCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(colorCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelsCheckBox)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(delayTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(delayLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(delaySlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(maxSandButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addOneGrainEverywhereButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(duelConfigButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 48, Short.MAX_VALUE)
                .add(clearSandButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(controlStateComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(optionsContainerPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 294, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(quitButton)
                .add(31, 31, 31))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
    //runTimer.setDelay( delaySlider.getValue());
    if(runTimer.isRunning()) {
        runTimer.stop();
    }else {
        runTimer.start();
    }
}//GEN-LAST:event_runButtonActionPerformed

private void stepButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stepButtonMouseClicked
	
}//GEN-LAST:event_stepButtonMouseClicked

private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
    System.exit(0);
}//GEN-LAST:event_quitButtonActionPerformed

private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
    sandpileViewPanel.update();
}//GEN-LAST:event_stepButtonActionPerformed

private void delayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delayTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_delayTextFieldActionPerformed

private void delaySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_delaySliderStateChanged
	runTimer.setDelay(delaySlider.getValue());
}//GEN-LAST:event_delaySliderStateChanged

private void controlStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlStateComboBoxActionPerformed
	sandpileViewPanel.setControlState(controlStateComboBox.getSelectedIndex());

}//GEN-LAST:event_controlStateComboBoxActionPerformed

private void maxSandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxSandButtonActionPerformed
	sandpileViewPanel.maxStableConfig();
}//GEN-LAST:event_maxSandButtonActionPerformed

private void clearSandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSandButtonActionPerformed
	sandpileViewPanel.clearSand();
}//GEN-LAST:event_clearSandButtonActionPerformed

private void addOneGrainEverywhereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOneGrainEverywhereButtonActionPerformed
	sandpileViewPanel.addSandEverywhere(1);
}//GEN-LAST:event_addOneGrainEverywhereButtonActionPerformed

private void gridRowsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridRowsFieldActionPerformed
	//sandpileViewPanel.setGridRows( Integer.parseInt(gridRowsField.getText() ) );
}//GEN-LAST:event_gridRowsFieldActionPerformed

private void gridColsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridColsFieldActionPerformed
	//sandpileViewPanel.setGridCols( Integer.parseInt( gridColsField.getText() ) );
}//GEN-LAST:event_gridColsFieldActionPerformed

private void gridRowsFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gridRowsFieldPropertyChange
// TODO add your handling code here:
}//GEN-LAST:event_gridRowsFieldPropertyChange

private void numOfGrainsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfGrainsFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_numOfGrainsFieldActionPerformed

private void controlStateComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_controlStateComboBoxItemStateChanged
	String currentState = (String)evt.getItem();
	CardLayout cl = (CardLayout)(optionsContainerPanel.getLayout());
	//cl.show(optionsContainerPanel, (String)evt.getItem());
	if(currentState.equals(ADD_SAND_STATE)||currentState.equals(DEL_SAND_STATE)) {
		cl.show(optionsContainerPanel, ADD_SAND_STATE);
	}else if(currentState.equals(MAKE_GRID_STATE) || currentState.equals(MAKE_HEX_GRID_STATE)){
		cl.show(optionsContainerPanel, MAKE_GRID_STATE);
	}else if(currentState.equals(ADD_EDGE_STATE)||currentState.equals(DEL_EDGE_STATE)||currentState.equals(ADD_UNDI_EDGE_STATE)|| currentState.equals(DEL_UNDI_EDGE_STATE)) {
		cl.show(optionsContainerPanel, ADD_EDGE_STATE);	
	}else if(currentState.equals(ADD_VERTEX_STATE) || currentState.equals(DEL_VERTEX_STATE) ) {
		cl.show(optionsContainerPanel, ADD_VERTEX_STATE);	
	}
}//GEN-LAST:event_controlStateComboBoxItemStateChanged

private void sandpileViewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sandpileViewPanelMouseClicked

}//GEN-LAST:event_sandpileViewPanelMouseClicked

private void weightFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_weightFieldActionPerformed

private void sandpileViewPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sandpileViewPanelMouseReleased
	String currentState = (String) controlStateComboBox.getSelectedItem();
	int x = evt.getX();
	int y = evt.getY();
	if(currentState.equals(ADD_SAND_STATE)) {
		sandpileViewPanel.addSandControl(x,y, Integer.valueOf(numOfGrainsField.getText() ) );
	}else if(currentState.equals(DEL_SAND_STATE)){
		sandpileViewPanel.addSandControl(x,y, -Integer.valueOf(numOfGrainsField.getText() ) );
	}else if(currentState.equals(MAKE_GRID_STATE)){
		sandpileViewPanel.makeGrid2(Integer.valueOf(gridRowsField.getText()), Integer.valueOf(gridColsField.getText()), x, y, 
				nBorderComboBox.getSelectedIndex(), 
				sBorderComboBox.getSelectedIndex(), 
				eBorderComboBox.getSelectedIndex(), 
				wBorderComboBox.getSelectedIndex());
	}else if(currentState.equals(MAKE_HEX_GRID_STATE)){
		sandpileViewPanel.makeHexGrid(Integer.valueOf(gridRowsField.getText()), Integer.valueOf(gridColsField.getText()), x, y, 
				nBorderComboBox.getSelectedIndex(), 
				sBorderComboBox.getSelectedIndex(), 
				eBorderComboBox.getSelectedIndex(), 
				wBorderComboBox.getSelectedIndex());
	}else if(currentState.equals(ADD_EDGE_STATE)) {
		sandpileViewPanel.addEdgeControl(x, y, Integer.valueOf(weightField.getText()));
	}else if(currentState.equals(DEL_EDGE_STATE)) {
		sandpileViewPanel.delEdgeControl(x, y, Integer.valueOf(weightField.getText()));
	}else if(currentState.equals(ADD_UNDI_EDGE_STATE)) {
		sandpileViewPanel.addUndiEdgeControl(x, y, Integer.valueOf(weightField.getText()));
	}else if(currentState.equals(DEL_UNDI_EDGE_STATE)) {
		sandpileViewPanel.delUndiEdgeControl(x, y, Integer.valueOf(weightField.getText()));
	}else if(currentState.equals(ADD_VERTEX_STATE)) {
		sandpileViewPanel.addVertexControl(x, y);
	}else if(currentState.equals(DEL_VERTEX_STATE)) {
		sandpileViewPanel.delVertexControl(x, y);
	}
}//GEN-LAST:event_sandpileViewPanelMouseReleased

private void nBorderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBorderComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nBorderComboBoxActionPerformed

private void sBorderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBorderComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_sBorderComboBoxActionPerformed

private void eBorderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBorderComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_eBorderComboBoxActionPerformed

private void wBorderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wBorderComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_wBorderComboBoxActionPerformed

private void repaintCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repaintCheckBoxActionPerformed
	sandpileViewPanel.setRepaint(repaintCheckBox.isSelected() );
}//GEN-LAST:event_repaintCheckBoxActionPerformed

private void colorCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorCheckBoxActionPerformed
	sandpileViewPanel.setColor(colorCheckBox.isSelected());
}//GEN-LAST:event_colorCheckBoxActionPerformed

private void labelsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelsCheckBoxActionPerformed
	sandpileViewPanel.setLabels(labelsCheckBox.isSelected());
}//GEN-LAST:event_labelsCheckBoxActionPerformed

private void duelConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duelConfigButtonActionPerformed
	sandpileViewPanel.setToDuelConfig();
}//GEN-LAST:event_duelConfigButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sandpiles().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addEdgeOptionsPanel;
    private javax.swing.JButton addOneGrainEverywhereButton;
    private javax.swing.JPanel addSandOptionsPanel;
    private javax.swing.JPanel blankOptionsPanel;
    private javax.swing.JButton clearSandButton;
    private javax.swing.JCheckBox colorCheckBox;
    private javax.swing.JComboBox controlStateComboBox;
    private javax.swing.JLabel delayLabel;
    private javax.swing.JSlider delaySlider;
    private javax.swing.JTextField delayTextField;
    private javax.swing.JButton duelConfigButton;
    private javax.swing.JComboBox eBorderComboBox;
    private javax.swing.JTextField gridColsField;
    private javax.swing.JTextField gridRowsField;
    private javax.swing.JLabel gridSizeCrossLabel;
    private javax.swing.JLabel gridSizeLabel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox labelsCheckBox;
    private javax.swing.JPanel makeGridOptionsPanel;
    private javax.swing.JButton maxSandButton;
    private javax.swing.JComboBox nBorderComboBox;
    private javax.swing.JTextField numOfGrainsField;
    private javax.swing.JPanel optionsContainerPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JCheckBox repaintCheckBox;
    private javax.swing.JToggleButton runButton;
    private javax.swing.JComboBox sBorderComboBox;
    private SandpilePanel sandpileViewPanel;
    private javax.swing.JButton stepButton;
    private javax.swing.JComboBox wBorderComboBox;
    private javax.swing.JTextField weightField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}